name: flutter_bantu_wallet_module_example
description: "A Flutter application showcasing how to use the flutter_bantu_wallet_module package"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  easy_localization: ^3.0.7
  flutter:
    sdk: flutter
  flutter_bantu_wallet_module:
    path: ..
  flutter_modular: ^6.3.4
  hive: ^2.2.3
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - packages/flutter_bantu_wallet_module/assets/i18n/
