name: flutter_bantu_wallet_module_example
description: "A Flutter application showcasing how to use the flutter_bantu_wallet_module package"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_bantu_wallet_module:
    path: ..
  flutter_modular: ^6.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
