targets:
  $default:
    sources:
      - lib/**
      - swaggers/**
      - $package$
    builders:
      swagger_dart_code_generator:
        options:
          input_folder: "lib/swaggers/"
          output_folder: "lib/src/features/wallets/data/data_sources/swagger/bantubeat"
          input_urls:
            - url: "https://raw.githubusercontent.com/gogovan/swagger-demo-flutter/refs/heads/main/swagger_demo/lib/swaggers/auth_api.json"
              file_name: "gogovan_auth_api.json"
          #input_urls:
          #  - url: "https://api.dev.bantubeat.com/docs/content"
          #    file_name: "bantubeat_api.json"
          separate_models: true
          use_path_for_request_names: true
          #exclude_paths:
          #  - "/cars/get"
          include_paths:
            - "/auth/user"
            - "/public/currencies"
            - "/public/all-currencies"
            - "/public/generate-withdrawal-payment-slip"
            - "/public/exchange-bzc-packs"
            - "/exchanges/bzc_to_fiat"
            - "/exchanges/fiat_to_bzc"
            - "/balance"
            - "/balance/transactions"
            - "/balance/can-i-make-a-withdrawals"
            - "/balance/withdrawals"
            - "/balance/withdrawal/requests"
            - "/deposit-payment/request-payment-link"
            - "/deposit-payment/payment-status/{uuid}"
