name: flutter_bantu_wallet_module
description: A wallet module for bantubeat eco system apps.
# publish_to: 'none'
version: 1.0.0

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  awesome_dio_interceptor: ^1.3.0
  dio: ^5.7.0
  dio_cache_interceptor: ^3.5.0
  dio_cache_interceptor_hive_store: ^3.2.2
  easy_localization: ^3.0.7
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_modular: ^6.3.4
  flutter_paypal_native: ^2.1.0
  flutter_screen_controller: ^0.0.5+1
  flutter_stripe: ^11.3.0
  flutter_svg: ^2.0.15
  fluttertoast: ^8.2.8
  flutterwave_standard_smart: ^1.0.4
  google_fonts: ^6.2.1
  hive: ^2.2.3
  hydrated_bloc: ^9.1.5
  moment_dart: ^2.2.1+beta.0
  pay: ^2.0.0
  select_form_field: ^2.2.0
  skeletonizer: ^1.4.2
  swagger_parser: ^1.19.2
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/i18n/
    - assets/images/
