name: flutter_bantu_wallet_module
description: A wallet module for bantubeat eco system apps.
# publish_to: 'none'
version: 1.0.3

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  awesome_dio_interceptor: ^1.3.0
  dio: ^5.7.0
  dio_cache_interceptor: ^3.5.0
  dio_cache_interceptor_hive_store: ^3.2.2
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_modular: ^6.3.4
  flutter_screen_controller: ^0.0.5+1
  flutter_svg: ^2.0.15
  flutter_vector_icons: ^2.0.0
  fluttertoast: ^8.2.8
  google_fonts: ^6.2.1
  hive: ^2.2.3
  infinite_scroll_pagination: ^4.1.0
  intl: ^0.19.0
  loader_overlay: 4.0.3
  pay: ^2.0.0
  select_form_field: ^2.2.0
  skeletonizer: ^1.4.2
  url_launcher: ^6.3.1
  webview_flutter: ^4.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  easy_localization: ^3.0.7 # Just to generate LocaleKeys

flutter:
  uses-material-design: true
